### ISSUE TITLE
[ADD-RPC] Add Crab RPC endpoint rpc.yalpha.io

### ISSUE THREAD

**Issue by hackfisher** [dcdao/community-rpc#10]
### Chain

Crab

### Http Endpoint

http://rpc.yalpha.io:9955

### Websocket Endpoint

ws://rpc.yalpha.io:9966

### Address

0x7C9B3D4cfc78c681B7460acdE2801452aEF073A9

**Comment by fewensa** [comment]
It's looks like your node is not an archive node, please follow our documents use snapshots and add `--pruning=archive` to your boot command. new version substrate you should change to `--state-pruning=archive`


Suggest you add `--ws-max-connections=1000` to your boot command.


Related: https://docs.darwinia.network/how-to-become-a-collator-af6bce360d5b49ddacc56e4587510210#3a572fe8ac9342f987c9c59831a4d717

```bash
$ curl -X POST -H 'Content-Type: application/json' http://rpc.yalpha.io:9955 -d '{"id":26,"jsonrpc":"2.0","method":"state_getRuntimeVersion","params":["0x3132433dfe794cdd5ca8955a5eda920925089a0398578b5718010e936522f857"]}'
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Client error: Api called for an unknown Block: State already discarded for 0x3132433dfe794cdd5ca8955a5eda920925089a0398578b5718010e936522f857"},"id":26}
```

**Comment by wuminzhe** [comment]
old:
```
--pruning=archive
```

new:
```
--state-pruning=archive \
--blocks-pruning=archive
```
