### ISSUE TITLE
[ADD-RPC] hukfrog

### ISSUE THREAD

**Issue by hukfrog** [dcdao/community-rpc#3]
### Chain

Darwinia

### Http Endpoint

http://54.250.172.141:9933

### Websocket Endpoint

ws://54.250.172.141:9933

### Address

0x3C7533361d051Fa9eA2D730FF852b7b0214E3A0F

**Comment by fewensa** [comment]
I'm already add pull request, but please wait #2 , Thank you for your participation

**Comment by fewensa** [comment]
Merged to community rpc provider, Thanks! https://github.com/dcdao/community-rpc/pull/4
